version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: install libsnappy-dev
        command: sudo apt install -y libsnappy-dev
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  benchmark:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: benchmark
  snappy-benchmark:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: snappy-benchmark
  docs:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: docs
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: lint
  py36-core-asyncio:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-core-asyncio
  py36-core-trio:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-core-trio
  py37-core-asyncio:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core-asyncio
  py37-core-trio:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core-trio
  py36-examples:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-examples
  py37-examples:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-examples
  py36-snappy-core-asyncio:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-snappy-core-asyncio
  py36-snappy-core-trio:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-snappy-core-trio
  py37-snappy-core-asyncio:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-snappy-core-asyncio
  py37-snappy-core-trio:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-snappy-core-trio
workflows:
  version: 2
  test:
    jobs:
      - benchmark
      - snappy-benchmark
      - docs
      - lint
      - py36-core-asyncio
      - py36-core-trio
      - py36-examples
      - py37-examples
      - py37-core-asyncio
      - py37-core-trio
      - py36-snappy-core-asyncio
      - py36-snappy-core-trio
      - py37-snappy-core-asyncio
      - py37-snappy-core-trio
